### ISSUE TITLE
Lodash version used here is vulnerable to prototype pollution and can't be bumped up with breaking the code

### ISSUE THREAD

**Issue by johndallen** [lennym/i18n-future#12]
We've been getting severe NPM audit errors relating to Lodash prototype pollution in version 3.7.0.
When upgrading to a version of Lodash which has a fix, the package no longer works correctly.  Any chance the version of Lodash could be upgraded so that it fixes the vulnerabilities and still works as before?

**Comment by lennym** [comment]
Thanks. I'll take a look.

**Comment by johndallen** [comment]
If it's any help:

TypeError: Cannot read property 'en-US' of undefined
    at /projects/blah/node_modules/i18n-future/lib/translator.js:72:46
    at arrayReduce (/projects/blah/node_modules/i18n-future/node_modules/lodash/lodash.js:675:21)

**Comment by lennym** [comment]
I've published a new version - 2.0.0 which passes all the pre-existing unit tests, but with many dependencies updated and a clean `npm audit`.

Not it swaps a few things to use arrow functions (the reason it broke with up-to-date `lodash` is because of lodash removing optional arguments for lexical binding) instead of explicit binding so it _might_ break on ancient runtimes, but I'm guessing that if you care about `npm audit` passing then you're not on an ancient runtime.

**Comment by johndallen** [comment]
Thanks for the quick turnaround.  I've updated to use 2.0.0 and the NPM audit vulnerabilities have gone away.
